### get task
POST localhost:4444/task

### get wisdom
POST localhost:4444/wisdom
Jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUYXNrIjp7IkFsZyI6InNoYTI1NiIsIklucHV0UHJlZml4IjoiZjJhN2VjNTAtNTY3MC00ZTMzLTk0NWUtMzFhOTFmM2NhNWQxIiwiTXVzdENvbnRhaW5MZWFkaW5nWmVyb3MiOjF9LCJJUCI6IjEyNy4wLjAuMSIsImV4cCI6MTY5MDQ4Mzk3NX0.EssdDEK_FBrkNcmc__1j-90eJk3GQ7vww34TOTogVv0

35b4b08f-e553-4782-9838-8c27a7b4eb98:try:484

